#!usr/bin/tamfan/install/metasploit/perl
#Mau Hubungi Gua ? 0857-8041-1404 && 0859-6634-6141
use Term::ANSIColor;
use if $^O eq "MSWin32", Win32::Console::ANSI;
use POSIX qw(strftime);
@months = qw( Januari Februari Maret April Mei Juni Juli Agustus September Oktober November Desmber );
@days = qw(Minggu Senin Selasa Rabu Kamis Jumat Sabtu Minggu);
$years = strftime "%Y", gmtime;
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();
mrtamfanx();
sub mrtamfanx {
if ($^O =~ /MSWin32/) {system("mode con: cols=100 lines=29");system("cls"); }else { system("resize -s 28 87");system("clear"); }
print color('bold cyan'),"┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n";
print color('bold cyan'),"┃  ";
print color('bold red'),"Author ";
print color('bold green'),": ";
print color('bold white'),"MrTamfanX ";
print color('bold yellow'),"- ";
print color('bold green'),"WhatsApp : 62 857";
print color('bold white'),"-";
print color('bold green'),"8041";
print color('bold white'),"-";
print color('bold green'),"1404  ";
print color('bold cyan'),"┃\n";
print color('bold cyan'),"┃  ";
print color('bold blue'),"Facebook Page ";
print color('bold yellow'),"& ";
print color('bold blue'),"Instagram ";
print color('bold green'),": ";
print color('bold yellow'),"MrTamfanX Cyber Team  ";
print color('bold cyan'),"┃\n";
print color('bold cyan'),"┃  ";
print color('bold yellow'),"PENG-INSTALLAN METASPLOIT DAN SIAPKAN RUANG ANDA  ";
print color('bold cyan'),"┃\n";   
print color('bold cyan'),"┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n";
print color('bold red'),"┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\n";
print color('bold white'),"[";
print color('bold red'),"•";
print color('bold white'),"]";
print color('bold white'),"Tanggal ";
print color('bold green'),": ";
print color('bold yellow'),"$mday ";
print color('bold white'),"Hari ";
print color('bold green'),": ";
print color('bold yellow'),"$days[$wday] ";
print color('bold white'),"Bulan ";
print color('bold green'),": ";
print color('bold yellow'),"$months[$mon] ";
print color('bold white'),"Tahun ";
print color('bold green'),": ";
print color('bold yellow'),"$years\n";
print color('bold white'),"[";
print color('bold red'),"•";
print color('bold white'),"]";
print color('bold white'),"Jam ";
print color('bold green'),": ";
print color('bold yellow'),"$hour ";
print color('bold green'),": ";
print color('bold yellow'),"$min ";
print color('bold green'),": ";
print color('bold yellow'),"$sec\n\n";
print color('bold white'),"[";
print color('bold red'),"•";
print color('bold white'),"]";
print color('bold yellow')," Tunggu Sampai Proses Peng-installan Selesai\n";
print color('bold white'),"";
sleep(5);
system('pkg install unstable-repo');
system('pkg install metasploit');
print color('bold white'),"[";
print color('bold green'),"✓";
print color('bold white'),"]";
print color('bold cyan')," SUDAH SELESAI DAN KAMI AKAN JALANKAN METASPLOITNYA\n";
print color('bold white'),"";
print color('bold green')," NEXT ";
print color('bold white'),"]";
print color('bold cyan')," KETIK YES UNTUK LANJUT ";
print color('bold green'),": ";
print color('bold white'),"";
chomp($akas=<STDIN>);
if($akas eq 'YES'){
mrtamfanx2();
system('msfconsole');
}if($akas eq 'yes'){
system('msfconsole');
}
}
sub mrtamfanx2 {
if ($^O =~ /MSWin32/) {system("mode con: cols=100 lines=29");system("cls"); }else { system("resize -s 28 87");system("clear"); }
print color('bold cyan'),"┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n";
print color('bold cyan'),"┃  ";
print color('bold red'),"Author ";
print color('bold green'),": ";
print color('bold white'),"MrTamfanX ";
print color('bold yellow'),"- ";
print color('bold green'),"WhatsApp : 62 857";
print color('bold white'),"-";
print color('bold green'),"8041";
print color('bold white'),"-";
print color('bold green'),"1404  ";
print color('bold cyan'),"┃\n";
print color('bold cyan'),"┃  ";
print color('bold blue'),"Facebook Page ";
print color('bold yellow'),"& ";
print color('bold blue'),"Instagram ";
print color('bold green'),": ";
print color('bold yellow'),"MrTamfanX Cyber Team  ";
print color('bold cyan'),"┃\n";
print color('bold cyan'),"┃  ";
print color('bold yellow'),"PENG-INSTALLAN METASPLOIT DAN SIAPKAN RUANG ANDA  ";
print color('bold cyan'),"┃\n";   
print color('bold cyan'),"┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n";
print color('bold red'),"┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\n";
print color('bold white'),"[";
print color('bold red'),"•";
print color('bold white'),"]";
print color('bold white'),"Tanggal ";
print color('bold green'),": ";
print color('bold yellow'),"$mday ";
print color('bold white'),"Hari ";
print color('bold green'),": ";
print color('bold yellow'),"$days[$wday] ";
print color('bold white'),"Bulan ";
print color('bold green'),": ";
print color('bold yellow'),"$months[$mon] ";
print color('bold white'),"Tahun ";
print color('bold green'),": ";
print color('bold yellow'),"$years\n";
print color('bold white'),"[";
print color('bold red'),"•";
print color('bold white'),"]";
print color('bold white'),"Jam ";
print color('bold green'),": ";
print color('bold yellow'),"$hour ";
print color('bold green'),": ";
print color('bold yellow'),"$min ";
print color('bold green'),": ";
print color('bold yellow'),"$sec\n\n";
}
